# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dd9047c862e8882a70703175ca7123c467263b82203ce417ea13b68a7c4d0cf098ce69097684a3a64ae7991fd5111b948de576036158543efb2bca26967a5b4

test:
  secret_key_base: 30b1d11359af2c9879dc7ba499970069c95775f7fe2c95f0ed8d389f0719ce111b2146269a0e5bafc3e8e056790a874d973b7b6f433b1b9755393fba48dc61a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
